### ISSUE TITLE
Missing Tabs component (TabLayout)

### ISSUE THREAD

**Issue by leocavalcante** [invertase/react-native-material-design#29]
Guys, first of all: awesome project.
I'm just missing the [Tabs Component](https://www.google.com/design/spec/components/tabs.html) which is a [TabLayout](http://developer.android.com/reference/android/support/design/widget/TabLayout.html) implementation (I guess).
Any plans?

**Comment by Ehesp** [comment]
Hello

On another app I've managed to implement https://github.com/brentvatne/react-native-scrollable-tab-view pretty well, very easy to style.

Wasn't sure it was something that was needed since there's quite a lot of view pager/tab libs out there

**Comment by leocavalcante** [comment]
Right,
and what about a component that wraps one of this libraries to provide Material design? It will use the already founded implementation, but will apply fonts, colors and styles to ScrollableTabView assembling Material design and following the hole app. Basically, a bridge for react-native-material-design-styles and react-native-scrollable-tab-view.

**Comment by Ehesp** [comment]
I can do that yeah. Will have to use it as a dependancy but I guess it's pretty handy to have. Could also do something manual too, which allows for off screen horizontal scrolling (use this in another project myself)?

**Comment by leocavalcante** [comment]
You could have a fork from scrollable-tab-view (or another one) for react-native-material-design team to avoid vendor-lockin, it will require extra efforts to follow up original project updates, buuuut, despite avoiding vendor-lockin you can transform it in something better also.
